### PR TITLE
Fix named types/modes

### LINKED ISSUE #24: interpreter doesn't handle modes correctly - unknown batch mode
```mips
lb r0 HASH("ItemActiveVent") On Maximum
```

gives

```
unknown batch mode '23'
```

where batchmode is interpreted as logictype `Maximum=23`

### PR DESCRIPTION
**Pull request by Emilgardis**
this doesn't work currently

resolves #24
depends on #26

### CODE REVIEW

**Comment by Emilgardis** [comment]
should probably add some regression tests to catch these kind of errors, pretty sure this used to work correctly

**Comment by Ryex** [comment]
Just tested, seems to fix the issue now. also no panics :)

File: ic10emu/src/grammar.rs [hunk 1]
```diff
@@ -368,27 +370,25 @@ impl Operand {
...
+                } else if let Some(slt) = slot_logic_type {
+                    Ok(slt.get_str("value").unwrap().parse::<u16>().unwrap() as f64)
+                } else if let Some(bm) = batch_mode {
+                    Ok(bm.get_str("value").unwrap().parse::<u8>().unwrap() as f64)
+                } else if let Some(rm) = reagent_mode {
+                    Ok(rm.get_str("value").unwrap().parse::<u8>().unwrap() as f64)
+                } else {
+                    Err(interpreter::ICError::TypeValueNotKnown)
+                }
+            }
```
Comment (Emilgardis) [inline ic10emu/src/grammar.rs:391]: should not use unwrap here for the get i think, I'm pretty sure it'll always succeed but to be on the safe side
